version: '3.6'
services:
  selenium:
    image: selenium/standalone-chrome
    ports:
      - 4444:4444

  postgres:
    image: postgres:12.3
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

  market_analysis:
    image: niklss/market_analysis:1
    container_name: market_analysis_1
    command: >
      bash -c "python manage.py makemigrations
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - selenium
      - postgres
