# Generated by Django 3.0.7 on 2020-07-01 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hh_id', models.IntegerField(unique=True)),
                ('name', models.TextField(null=True)),
                ('link', models.TextField(null=True)),
                ('salary_from', models.IntegerField(null=True)),
                ('salary_to', models.IntegerField(null=True)),
                ('company_name', models.TextField(null=True)),
                ('link_to_company', models.TextField(null=True)),
                ('responsibility', models.TextField(null=True)),
                ('requirement', models.TextField(null=True)),
                ('date', models.DateTimeField(null=True)),
                ('required_experience', models.TextField(null=True)),
                ('employment_mode', models.TextField(null=True)),
                ('schedule', models.TextField(null=True)),
                ('key_skills', models.TextField(null=True)),
                ('city', models.TextField(null=True)),
                ('salary_in', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'vacancy',
            },
        ),
    ]
