# Generated by Django 3.0.7 on 2020-07-01 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'vacancy', 'verbose_name_plural': 'vacancies'},
        ),
        migrations.AddField(
            model_name='vacancy',
            name='region',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
