# Generated by Django 3.0.7 on 2020-07-03 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_auto_20200701_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='hh_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cv',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='salary',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='hh_id',
            field=models.IntegerField(),
        ),
    ]
