# Generated by Django 3.0.7 on 2020-07-03 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_auto_20200703_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='query',
            field=models.TextField(default='Тестировщик'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv',
            name='region',
            field=models.IntegerField(default='4'),
            preserve_default=False,
        ),
    ]
