# Generated by Django 3.0.7 on 2020-07-06 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_auto_20200703_0154'),
    ]

    operations = [
        migrations.CreateModel(
            name='statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy_average_from', models.IntegerField(verbose_name='Average starting salary')),
                ('vacancy_average_to', models.IntegerField(verbose_name='Average ending salary')),
                ('vacancy_average_experience', models.IntegerField(verbose_name='Average experience')),
                ('cv_average_salary', models.IntegerField(verbose_name='Average salary')),
                ('cv_average_experience', models.IntegerField(verbose_name='Average experience')),
                ('cv_average_age', models.IntegerField(verbose_name='Average age')),
                ('region', models.IntegerField()),
                ('query', models.TextField()),
            ],
            options={
                'verbose_name': 'Statistic',
                'verbose_name_plural': 'Statistics',
            },
        ),
    ]
