# Generated by Django 3.0.7 on 2020-07-06 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_statistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='cv_average_age',
            field=models.IntegerField(null=True, verbose_name='Average age'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='cv_average_experience',
            field=models.IntegerField(null=True, verbose_name='Average experience'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='cv_average_salary',
            field=models.IntegerField(null=True, verbose_name='Average salary'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='vacancy_average_experience',
            field=models.IntegerField(null=True, verbose_name='Average experience'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='vacancy_average_from',
            field=models.IntegerField(null=True, verbose_name='Average starting salary'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='vacancy_average_to',
            field=models.IntegerField(null=True, verbose_name='Average ending salary'),
        ),
    ]
